### ISSUE TITLE
Proposition d'amélioration: Fichiers structurels pour garder une feuille de TD en mémoire

### ISSUE THREAD

**Issue by jjfPCSI1** [mbrebion/exerciceExplorer#2]
Il me semble qu'il serait judicieux de pouvoir sauvegarder la structure d'une feuille de TD par exemple dans un fichier externe (à stocker sur la machine de l'utilisateur dans un dossier adéquat) pour qu'il ne faille pas chaque année reprendre chaque exercice dans la base pour constituer le document.

La structure du fichier pourrait être quelque chose du style 
```
# type: TD
# numero: T4
# titre: Premier principe

compression_en_deux_etapes
cycle_brayton
vaporisation
...
```

L'idée étant que l'explorateur d'exercice propose à la fois de sauvegarder un fichier de ce type une fois qu'on a fait une sélection manuelle et de pouvoir charger un fichier de ce type pour prendre les améliorations qui auraient été proposées d'une année sur l'autre.

Les infos de l'entête servant pour choisir le bon template et remplir les champs adéquats.

**Comment by mbrebion** [comment]
L’idée me parait bien mais n’est pas simple à implémenter : 
 - où stocker ces fichiers en local ?
 - comment ajouter l’info dans l’interface graphique (à mon avis, à partir du menu en haut dans l’item Fichier)
 - comment exporter ce fichier

**Comment by jjfPCSI1** [comment]
Il s'agit en fait déjà d'une issue sur GitHub qui t'a envoyé un mail pour te prévenir avec le contenu (et ta réponse a tout de suite été mise dans l'issue en question). Dans le mail, il doit y avoir un lien «View it on GitHub» tout en bas qui te permet d'y accéder directement.

Sinon pour ce qui est des questions:
* _où stocker ces fichiers en local_: soit dans un dossier du dépôt github qui soit explicitement dans le `.gitignore` pour que rien qui y soit mis ne soit envoyé sur GitHub (par exemple `feuilles_exos` que l'on pourrait peupler une première fois puis demander qu'il soit ignorer en cas de modification), soit il faut demander un chemin d'accès supplémentaire dans les options.
* _comment ajouter l’info dans l’interface graphique_: Effectivement, après «Nouvel exercice», un item «Nouvelle fiche d'exercices» serait adéquat.
* _comment exporter ce fichier_: à mon sens, il suffit d'un simple fichier .txt (pour que ce soit facilement éditable avec `open`) dans le dossier défini plus haut. Reste à voir aussi s'il faut une arborescence pour distinguer les différents types de devoirs (moi j'aime bien avoir un dossier pour les TD, un pour les DM, un pour les DS, etc.). Par exemple, on pourrait avoir une structure du type
```
feuilles_exos
├── DM
├── DS
│   ├── thermo_debut.txt
│   └── thermo_machines.txt
├── TD
│   ├── premier_principe.txt
│   └── second_principe.txt
└── colles
    ├── PCSI_S01_01.txt
    ├── PCSI_S01_02.txt
    ├── PCSI_S01_03.txt
    ├── PCSI_S02_01.txt
    ├── PCSI_S02_02.txt
    ├── PCSI_S02_03.txt
    └── PC_S01_01.txt
```

Note qu'une fois que la lecture du fichier est faite, l'interface pourra exporter la feuille d'exos en complétant le nom de manière adéquate avec les infos `type` et `numero`. Par exemple pour le TD du premier principe que j'ai donné en exemple tout au début et dont le numéro est «T4» dans ma nomenclature personnelle, l'export pourrait automatiquement renommer le fichier `.tex` ainsi que le `.pdf` produit en `TDT4_premier_principe.pdf`

NB: j'ai mis cette issue dans le dépôt github de l'explorateur plutôt que dans celui de la base (puisqu'il faut que l'explorateur puisse gérer tous ces fichiers), mais cela peut être utile de le signaler aussi dans le dépôt de la base, ce que je vais faire de ce pas.

NB2: pour les colles, je m'organise aussi comme cela avec le nom de la classe dans le nom du fichier et le nom de la semaine de colle correspondante. D'une année sur l'autre, les programmes de colle se suivent généralement assez bien, donc cela peut souvent resservir directement.

**Comment by mbrebion** [comment]
> Le 16 juil. 2020 à 16:14, Jean-Julien Joseph Fleck <notifications@github.com> a écrit :
> 
> 
> Il s'agit en fait déjà d'une issue sur GitHub qui t'a envoyé un mail pour te prévenir avec le contenu (et ta réponse a tout de suite été mise dans l'issue en question). Dans le mail, il doit y avoir un lien «View it on GitHub» tout en bas qui te permet d'y accéder directement.
> 
> 
Ok, je passe pour un noob là !  Il faudra que je desactive l’envoie du mail par défaut car je risque d’y répondre à chaque fois !
> Sinon pour ce qui est des questions:
> 
> où stocker ces fichiers en local: soit dans un dossier du dépôt github qui soit explicitement dans le .gitignore pour que rien qui y soit mis ne soit envoyé sur GitHub (par exemple feuilles_exos que l'on pourrait peupler une première fois puis demander qu'il soit ignorer en cas de modification), soit il faut demander un chemin d'accès supplémentaire dans les options.
> comment ajouter l’info dans l’interface graphique: Effectivement, après «Nouvel exercice», un item «Nouvelle fiche d'exercices» serait adéquat.
> comment exporter ce fichier: à mon sens, il suffit d'un simple fichier .txt (pour que ce soit facilement éditable avec open) dans le dossier défini plus haut. Reste à voir aussi s'il faut une arborescence pour distinguer les différents types de devoirs (moi j'aime bien avoir un dossier pour les TD, un pour les DM, un pour les DS, etc.). Par exemple, on pourrait avoir une structure du type
> feuilles_exos
> ├── DM
> ├── DS
> │   ├── thermo_debut.txt
> │   └── thermo_machines.txt
> ├── TD
> │   ├── premier_principe.txt
> │   └── second_principe.txt
> └── colles
>     ├── PCSI_S01_01.txt
>     ├── PCSI_S01_02.txt
>     ├── PCSI_S01_03.txt
>     ├── PCSI_S02_01.txt
>     ├── PCSI_S02_02.txt
>     ├── PCSI_S02_03.txt
>     └── PC_S01_01.txt
> Note qu'une fois que la lecture du fichier est faite, l'interface pourra exporter la feuille d'exos en complétant le nom de manière adéquate avec les infos type et numero. Par exemple pour le TD du premier principe que j'ai donné en exemple tout au début et dont le numéro est «T4» dans ma nomenclature personnelle, l'export pourrait automatiquement renommer le fichier .tex ainsi que le .pdf produit en TDT4_premier_principe.pdf
> 
> NB: j'ai mis cette issue dans le dépôt github de l'explorateur plutôt que dans celui de la base (puisqu'il faut que l'explorateur puisse gérer tous ces fichiers), mais cela peut être utile de le signaler aussi dans le dépôt de la base, ce que je vais faire de ce pas.
> 
> 
Oui, c’est un problème lié à l’éditeur et pas une fonctionalité de la bpep

> NB2: pour les colles, je m'organise aussi comme cela avec le nom de la classe dans le nom du fichier et le nom de la semaine de colle correspondante. D'une année sur l'autre, les programmes de colle se suivent généralement assez bien, donc cela peut souvent resservir directement.
> 
> —
> 

oui, c’est aussi pratique de ne pas retaper les questions de colle chaque année ;-)

**Comment by mbrebion** [comment]
L'idée me parait bien pensée pour les TDs et colles
Je vais commencer le développement dès ce week-end.

Par contre, pour le stockage des DM/DS, qui n'ont pas vocations à être réutilisés tels quels, je préfère plutôt la solution actuelle qui recopie en dur les exercices et tous les fichiers nécessaires à la compilation.
Cela permet de garder de manière pérenne la version donnée aux élèves et ce, même si quelqu'un améliore les exercices sur la bpep entre temps.
D'un autre côté, si je fais le boulot pour les TDs/Colles, c'est très simple de le faire aussi pour les DSs/DMs

**Comment by jjfPCSI1** [comment]
Oui, je pense que l'export est toujours très bien, y compris pour les colles et les TD d'ailleurs, ne serait-ce que pour pouvoir facilement partager le code LaTeX avec des collègues au besoin ou garder une trace pour soi.

**Comment by mbrebion** [comment]
Voilà, le repo git et le lien de DL direct sur mon site ont été mis à jours.
J'ai choisi de déclencher l'export depuis le bouton... "exporter" ! Ce dernier ouvre une fenêtre dans laquelle on peut choisir d'effectuer un export "copie" (solution actuelle) ou bien un export de liens (qui peut alors être ré-ouvert depuis l'IHM).
Le dossier feuilles_exos doit contenir au minimum les dossiers suivants :
 - DS
 - TD
 - Colle
 - DM

Cependant, en cas de présence de plusieurs dossier dont le nom débute par TD (ou DS, Colle ou DM), l'interface donnera le choix de celui à utiliser ; cela permet de séparer ces fiches de colle selon les classes.
