### ISSUE TITLE
[bug] bouton «commit» toujours allumé

### ISSUE THREAD

**Issue by jjfPCSI1** [mbrebion/exerciceExplorer#3]
Malgré le fait que je n'ai aucun changement à commiter (vérifié depuis le terminal et ce que confirme `git status`), le bouton «commit» est le seul qui est blanc (en plus du bouton «status»). Je ne sais pas trop ce que j'ai pu faire qui ait causé cela (peut-être un problème lié à la sauvegarde automatique que j'ai activée momentanément ?), mais en tous cas, quitter et revenir ne change rien au problème et si j'essaie de faire un commit en appuyant, il ne se passe rien (logique puisque `git` ne voit aucun changement à commiter).

![Capture d’écran 2020-07-16 à 14 03 31](https://user-images.githubusercontent.com/8352625/87669064-985fcf80-c76d-11ea-91be-158eb37d4c20.png)

Une idée de l'origine du problème ou de ce que je pourrais regarder pour corriger cela ?

**Comment by mbrebion** [comment]
Question bête : as-tu déposé ta clé publique ssh sur ton compte github (sans ça, l’IHM doit bloquer pour les commandes git push, git status et git pull et ça peut expliquer l’erreur)
autre possibilité : regarder depuis le terminal ce que git raconte (il faut pour cela se placer à la racine du dossier BPEP et taper un truc du genre "git fetch » puis ensuite "git status »)

**Comment by mbrebion** [comment]
Le problème était-il lié à la clé ssh publique ?

**Comment by jjfPCSI1** [comment]
Non, je ne pense pas car mes accès github fonctionnent sans problème sur mes autres projets. Néanmoins, après une mise à jour système, un redémarrage et l'utilisation de la dernière version de l'IHM, il n'y a plus de souci. Je viens de réussir à faire un commit et le bouton correspondant est à nouveau grisé. Je ferme donc cette issue jusqu'à ce que je retombe sur le bug en ayant une meilleure idée de son origine.

**Comment by mbrebion** [comment]
Ok, 
les bugs disparaissant d'eux-mêmes sont toujours très frustrants !

**Comment by jjfPCSI1** [comment]
Et le 🐛  revint, le jour suivant 🎵, et le 🐛  revint, il est toujours vivant 🎵 

Voici la capture d'écran que j'ai après avoir cliqué sur commit (alors que rien n'est à commiter), le bouton reste toujours allumé (`git status` me dit bien que je suis à jour)

![Capture d’écran 2020-07-24 à 14 51 51](https://user-images.githubusercontent.com/8352625/88393323-bd7fbe00-cdbd-11ea-9980-84739ce60856.png)

Pas de problème avec mon git car je peux tout faire normalement depuis la ligne de commande, mais il doit y avoir un test dans l'interface qu'il n'aime pas. Peut-être parce que justement je jongle entre les boutons de l'interface et le `git` direct en ligne de commande ?

**Comment by jjfPCSI1** [comment]
Trouvé, c'est parce que `git` se retrouve en français lorsque je lance l'application depuis le terminal. La prochaine version de l'IHM devrait corriger ce point.
