### ISSUE TITLE
Proposition d'amélioration (mineure): suppression des guillemets dans le texte des commits.

### ISSUE THREAD

**Issue by jjfPCSI1** [mbrebion/exerciceExplorer#4]
Actuellement, quand on fait un commit par l'interface, il y a des guillemets anglais «"» qui sont mis dans le texte du commit, par exemple `":pencil: $n$ en mode maths"` au lieu de `:pencil: $n$ en mode maths` directement.

Ont-ils une raison d'être particulière ou peuvent-ils être supprimés ?

**Comment by mbrebion** [comment]
Oui, je ne me souviens plus trop pourquoi mais je les ai ajoutés. Je peux les retirer mais pour prendre en compte ce changement, il faudra re-télecharger le logiciel (la nouvelle version gardera cependant tes réglages)

**Comment by mbrebion** [comment]
Les guillemets sont retirés ; Le changement sera visible dès maintenant sur le repo git et d'ici quelque temps pour la version autonome disponible sur mon site (j'attends d'effectuer d'autres modifications avant de publier une nouvelle version)

**Comment by jjfPCSI1** [comment]
Je confirme que cela fonctionne !
