### ISSUE TITLE
[Linux]  Pas de bouton quitter

### ISSUE THREAD

**Issue by ebachard** [mbrebion/exerciceExplorer#5]
Bonjour Maxence,

Ce n'est qu'une suggestion d'amélioration, mais quand je lance l'application, je n'ai pas de bouton " quitter ".  Est-ce normal ?

![exerciceExplorer_2020_07_17](https://user-images.githubusercontent.com/23149049/87820790-02ac6900-c86f-11ea-842a-519de71f9fc5.png)

OS : Linux (Linuxmint 19.2, Intel x86_64)

Pas de souci pour fermer l'issue si ma question est sans intérêt.

**Comment by mbrebion** [comment]
La croix en haut à droite non ?
(sous MacOS, j'avoue toujours taper "command+q" pour fermer une application donc je n'avais pas pensé à ça !)
J'ai ajouté un item "quitter" dans le menu fichier qui fera aussi le job.

**Comment by ebachard** [comment]
Ok, je vais regarder aussi. CTRL Q  devrait peut-être fonctionner (pas essayé). Merci pour l'ajout de l'item (en attendant, j'utilise ALT + F4)
