### ISSUE TITLE
[Linux]  Préférences non sauvegardées  + ressources non accessibles

### ISSUE THREAD

**Issue by ebachard** [mbrebion/exerciceExplorer#6]
Bonjour Maxence,

Je n'arrive pas à sauvegarder les préférences ni à afficher quoi que ce soit dans le cadre. Si je sélectionne l'onglet composition, quel que soit le type (DS, TD ..) la liste reste vide, et je ne peux pas saisir de mot clé (la boîte reste vide, et le curseur n'est pas détecté).

Autre problème (probablement lié) : quand je relance l'application, tout ce qui a été saisi est perdu, et je dois entrer à nouveau les chemins (est-ce normal ?). 

Ci-dessous, ce que j'ai utilisé : 

````
me@ma_machine~ $ type xdg-open
xdg-open est /usr/bin/xdg-open
me@ma_machine ~ $ type pdflatex 
pdflatex est /usr/bin/pdflatex
````

Pour les modeles j'ai mis ce chemin  (j'ai remplacé mon login par la commande qui le remplace, pour éviter de mettre mon login en ligne, mais le chemin saisi le contient ): 

````
(chemin_absolu_vers_bpep)/bpep/fichiers_utiles/defaultLatexTemplates
````
Et pour les ressources, j'ai mis:

````
(chemin_absolu_vers_bpep)/bpep/exercices

````

Je voulais voir si les exercices qui ont déja été écrits apparaissaient =>  rien.

ça ne doit pas être grand chose, mais pour l'instant, je n'ai pas trouvé.

Merci d'avance pour toute aide et/ou suggestion :-)

UPDATE : voici ce que j'obtiens quand j'essaye de créer un nouveau document:

![image](https://user-images.githubusercontent.com/23149049/87824466-9bde7e00-c875-11ea-872d-702097bf3a11.png)

On dirait que c'est vraiment un problème de path, alors que les fichiers sont bien là :

````
me@ma_machine $ pwd

(chemin_absolu_vers_bpep)/bpep/fichiers_utiles/defaultLatexTemplates

me@ma_machine $ ls
Collemodel.tex  DMmodel.tex  DSmodel.tex  TDModel.tex

````

Versions de java et ant :

````
 $ ant -version
Apache Ant(TM) version 1.10.5 compiled on March 28 2019
$ java --version
openjdk 11.0.7 2020-04-14

````

**Comment by mbrebion** [comment]
Question bête mais dans tes chemins d'accès, il n'y a pas un bpep en trop ?
N'hésites pas à m'envoyer les versions exactes des chemins d'accès sans le bloc (chemin_absolu_vers_bpep) sous Mattermost en privé.
Le problème du non-stockage des options m'inquiète aussi un peu.
Comment execute tu l'IHM (double click ou `java -jar exerciceExplorer`  depuis le terminal ?)

**Comment by ebachard** [comment]
AMHA, il n'y a pas de bpep en trop : pour définir mes préférences, j'ai simplement utilisé le résultat de " pwd ", que j'ai copié-collé dans la boîte de dialogue, et je ne pense pas que le chemin soit faux. J'ai ajouté une copie d'écran parce que le message d'erreur est bizzare : note le /  dans /DSModel.tex not found. On dirait que la construction du path ne marche pas bien sous Linux.

En fait, je vais mettre le nez dans le code(j'ai trouvé où c'est dans le code, et je vais faire des essais). Pour ça, j'ai installé ant  + un jdk qui devrait fonctionner, et je vais voir si je peux compiler ma propre version et faire des tests. Je te tiendrai au courant de mes avancées.

Il faudra être un peu patient, parce que je compte lever le nez de l'écran dans la semaine (mes yeux sont fatigués par une année passée derrière l'écran, et je vais faire une pause)

Pour ce qui est de l'exécution, j'ai tout essayé : dans le terminal, et avec un lanceur customisé. On dirait que l'environnement n'est pas reconnu. En général, c'est un truc tout bête qui cause ce genre de problème, et je ne m'en fais pas. Il y a quelques années, j'ai beaucoup galéré à cause de Java avec OpenOffice, surtout pour la version Mac OS X, dont je m'occupais, et je connais assez bien (les fondations de  java ne sont pas si clean, et dépendent souvent de détails) 

À suivre :-)

EDIT : la compilation fonctionne (sortie vide, mais c'est normal), ce qui signifie que pdflatex est trouvé.

**Comment by mbrebion** [comment]
Pour modifier/compiler les sources, je te recommande vivement l'IDE netbeans (c'est ce dernier qui a été utilisé pour le projet).
Quand tu quittes et que tu ré-ouvre le logiciel, le chemin d'accès de pdflatex reste dispo ?
Je soupçonne fortement que le code sauvegardant des options plante depuis ton PC ce qui explique le résultat étrange sur ton imprime écran (path=""  en faite).
Côté code, je te conseille de regarder du côté de SavedVariables dans le package Helper

**Comment by ebachard** [comment]
Bonjour,

Merci pour les indications, ça va me faire gagner du temps.

Je suis en train d'installer netbeans, mais je suis habitué à des grosses quantités de code en ligne de commande, et je testerai les 2. Ce qui est bien en installant netbeans, c'est que toutes les dépendances devraient être installées avec (et c'est précieux d'avoir un tel problème résolu).

**Comment by mbrebion** [comment]
Oui, c'est l'intérêt de l'IDE (surtout quand le projet à été développé avec).
J'ai écrit pas mal de projets en Java mais jamais sans IDE (j'ai un peu peur de ant/maven je pense !)

Le path de pdflatex est-il sauvegardé par l'appli ?
Sinon, le fait que la compilation fonctionne est assez curieux

**Comment by ebachard** [comment]
Je pense que le soft trouve les chemins basiques (comme /usr/bin) qui sont toujours dans l'environnement (et existant sur Macc OS X, mais pas les chemins qui dépendent de l'utilisateur.

Ce qu'on fait en général : on utilise (pour chaque OS) un chemin standard.  Par exemple, sous Mac OS X   /Users/`whoami`/Libraries/Application\ Support/ExerciceExplorer  (exemple bidon mais pas tant que ça pour illustrer)

Sous Linux, ça pourrait être /usr/share/ExercicesExplorer (installation pour tous les utilsateurs) ~/.config/ExercicesExplorer  pour chaque utilisateur. Au lancement, on cherche dans  ~/.config/ExercicesExplorer et ce qui n'est pas trouvé est cherché dans /usr/share/ExercicesExplorer (qui est toujours présent, et pas modificable par un utilisateur lambda).

**Comment by ebachard** [comment]
Ok, c'est résolu en recompilant le logiciel avec netbeans.

Il manquait les bonnes bibliothèques (symboles non résolus, c'est symptomatique). Merci d'avoir ajouté ces .jar dans les sources, c'est quand même plus simple.

Ne pas oublier d'ajouter ces .jar dans netbeans aussi, car le dossier qui contient les .jar n'est pas vu par défaut (testé avec un git clone de sources d'origines).

Une fois les .jar ajoutés dans netbeans, la compilation a pu se terminer, et j'ai pu saisir les chemins.

En relançant le logiciel, tout a été mémorisé, et tout semble fonctionner sous Linux (il me reste à bidouiller l'ajout du dictionnaire)

En résumé : 
- les préférences sont sauvegardées
- les ressources sont maintenant accessibles

**PROBLÈME RÉSOLU**   => tu peux fermer cette issue.
